build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
          CONAN_GCC_VERSIONS: 7
          ARCH: x86_64

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
